Разметка внутренних страниц
htmlacademy-adaptive/1385327-pink-25 pull request #3
Opened 2022-04-04 12:52 UTC by OksMor

Добавляет разметку формы и каталога

---
:mortar_board: [Разметка внутренних страниц](https://up.htmlacademy.ru/adaptive/25/user/1385327/tasks/3)

2022-04-04 18:25 UTC, mouxez requested changes

2022-04-04 18:25 UTC, mouxez commented on source/catalog.html
> +      <div class="gallery-photo__wrapper">
вот тут не по БЭМ
идеально - должно быть photo
у тебя все элементы внутри начинаются с photo

2022-04-04 18:25 UTC, mouxez commented on source/form.html
> +              <a class="header-navigation__link header-navigation__item--current" href="form.html">Конкурс</a>
модификатор нельзя использовать без основного класса
"header-navigation__item header-navigation__item--current"

2022-04-05 05:03 UTC, OksMor commented on source/catalog.html
> +      <div class="gallery-photo__wrapper">
Исправила на gallery__wrapper, по идее эта обертка у меня относилась к gallery.
В процессе стилизации я хотела бы попытаться от неё избавиться. (и наверное сейчас её правильнее бы было на 62ю строку поставить...)

2022-04-05 05:03 UTC, OksMor commented on source/form.html
> +              <a class="header-navigation__link header-navigation__item--current" href="form.html">Конкурс</a>
Промахнулась строчкой

2022-04-05 18:17 UTC, merged