Декоративные элементы внутренних страниц
htmlacademy-adaptive/1385327-pink-25 pull request #8
Opened 2022-05-03 15:18 UTC by OksMor

2022-05-03 19:10 UTC, mouxez requested changes

2022-05-03 19:10 UTC, brewscriptor commented on source/catalog.html
> +      <p class="information__title">Взгляни на фоторгафии, которые выкладывают пользователи!<br><span>Видите, как не хватает ваших?</span></p>
тут оборачивать в отдельный span не обязательно.
плиз, подскажи, для чего ты обернула?

2022-05-03 19:10 UTC, brewscriptor commented on source/catalog.html
> +              <button class="photo__statistic-button" type="button"><img src="img/catalog/heart.svg" width="13" height="12"
есть плагины для редактора кода, которые проверяют правильности написания слов на англ языке. рекомендую поискать такие в магазине плагинов редактора

2022-05-03 19:10 UTC, brewscriptor commented on source/catalog.html
> +            <button class="form-photo__button-editor">
у кнопки есть обязательный атрибут type

2022-05-03 19:10 UTC, mouxez commented on source/sass/blocks/catalog-information.scss
> +    padding-bottom: 75px;
тут наверно самое то место гда можно сокращённо написать значения для паддинга

2022-05-03 19:10 UTC, mouxez commented on source/sass/blocks/form-feedback.scss
> +  box-sizing: border-box;
вот это правило надо один раз в начале объявить и не менять по ходу всего проекта по хорошему

2022-05-04 04:30 UTC, OksMor commented on source/catalog.html
> +      <p class="information__title">Взгляни на фоторгафии, которые выкладывают пользователи!<br><span>Видите, как не хватает ваших?</span></p>
не обратила внимание, что тут не так как в форме, не исчезает второе предложение.

2022-05-04 04:31 UTC, OksMor commented on source/catalog.html
> +              <button class="photo__statistic-button" type="button"><img src="img/catalog/heart.svg" width="13" height="12"
да, надо поискать какой-нить плагин, а то, часто опечатки получаются, потом сидишь ищешь почему не работает...

2022-05-04 04:32 UTC, OksMor commented on source/sass/blocks/form-feedback.scss
> +  box-sizing: border-box;
ой, потеряшка, забыла удалить

2022-05-04 04:32 UTC, OksMor commented on source/sass/blocks/catalog-information.scss
> +    padding-bottom: 75px;
да, думаю можно

2022-05-05 05:05 UTC, merged